package christmas.enums;

public enum Menu {
    SOUP, TAPAS, CAESAR_SALAD,
    T_BONE_STEAK, BARBECUE_LIBS, SEAFOOD_PASTA, CHRISTMAS_PASTA,
    CHOCOLATE_CAKE, ICE_CREAM,
    ZERO_COKE, RED_WINE, CHAMPAGNE
}
